jenkins:
  systemMessage: "Welcome to Jenkins!"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

unclassified:
  location:
    url: "http://localhost:8080/"
  globalLibraries:
    libraries:
      - name: "jenkins-shared-library"
        defaultVersion: "master"
        implicit: true
        retriever:
          modernSCM:
            scm:
              github:
                repoOwner: "alexengrigtech"
                repository: "jenkins-shared-library"

jobs:
  - file: /var/jenkins_home/seedJob.groovy
